### ISSUE TITLE
Tooltip Component for Tutorial Window

### ISSUE THREAD

**Issue by NadavBitran** [NadavBitran/AR-Routing-UI#25]
## Background:
Our app will feature an interactive tutorial window that guides users through various features and functions. This training window is designed to provide a smooth learning experience by guiding the user through the process of managing routes.

## Current Situation:
The current situation prevents us from starting and progressing towards the creation of the tutorial, due to the lack of decision whether we prefer to use a 3rd party library or use a custom tooltip component which we will prepare in advance.

# Custom Tooltip Component:
Developing a custom tooltip component tailored to our application's specific needs could offer the following benefits:

* **Enhanced Customization:** We would have complete control over the tooltip's appearance and interactions, enabling us to match easily the tooltips with our application's design.

* **Flexible Interaction:** We could define when tooltips are displayed, how long they remain visible, and offer users the ability to manually dismiss them and to go the next step in the tutorial.

# 3rd Party Tooltip Component:
Using third-party tooltip library has its own set of advantages:

* **Time and Resource Efficiency**: Adopting a pre-existing solution could save development time and resources compared to building a custom component from scratch.

* **Possible Feature Updates**: Third-party libraries often receive updates and improvements, which could bring enhancements to our tooltips

## Summary:
We need to examine the tooltip issue, while trying to develop a custom tooltip component and at the same time experiment with an existing 3rd party tooltip component.

**Comment by MaorBezalel** [comment]
Hey @NadavBitran ,

Regarding 3rd party  solution, I think we should really look into [React Bootstrap](https://react-bootstrap.netlify.app/)
as they seem to offer many different useful components, including a `Tooltip` componant [here](https://react-bootstrap.netlify.app/docs/components/overlays/#tooltips).

Moreover, considering that React Bootstrap offers a wide range of components that are already designed and tested, we could even explore the possibility of replacing some of our  @custom-made components with their ready-to-use alternatives. This could save us development time and ensure a consistent and professional look and feel across our application.

I recommend discussing this further in our next meeting session to see how we can leverage React Bootstrap's offerings to enhance our project.
